<?PHP
define('MAIN_NAVIGATION', 'MAIN NAVIGATION');
define('INVENTORY', 'Inventory');
define('ADD_PRODUCTS', 'Add Products');
define('HOME', 'Home');
define('PRODUCT_NAME', 'Product Name');
define('UNIT_PRICE', 'Unit Price');
define('ADD_QUANTITY', 'Add Quantity');
define('SELECT_PRODUCT', 'Select Product');
define('HUMAN_RESOURCES', 'Human Resources');
define('ADD_EMPLOYEE', 'Add Employee');
define('NAME', 'Name');
define('EMAIL', 'Email');
define('ERORR_PROCEED', 'Please correct the errors to proceed.');
define('PRODUCT_SAVED', 'Thank you.New Product Updated.');
define('PLEASE_CHECK', 'Please Check');
define('PRODUCTS_LIST', 'Products List');
define('ID', 'ID');
define('EDIT', 'Edit');
define('DELETE', 'Delete');
define('QUANTITY', 'Quantity');
define('SEARCH', 'Search');
define('CUSTOMERS', 'Customers');
define('ADD_CUSTOMERS', 'Add Customers');
define('ACTION', 'Action');
define('ADD', 'Add');
define('SUBSTRACT', 'Subtract');
define('CUSTOMER_NAME', 'Customer Name');
define('ADDRESS', 'Address');
define('TELEPHONE', 'Telephone Number');
define('CUSTOMER_SAVED', 'Thank you.New Customer Updated.');
define('CUSTOMER_LIST', 'Customers List');
define('SALES', 'Sales');
define('ADD_SALE', 'Add Sale');
define('SELECT_CUSTOMER', 'Select Customer');
define('OR_TEXT', 'OR');
define('TAX_APPLICABLE', 'Tax applicable');
define('SALES_LIST', 'Sales List');
define('AMOUNT', 'Amount');
define('VIEW', 'View');
define('STATUS', 'Status');
define('NIC', 'Identity Card Number');
define('BIRTHDAY', 'Birthday');
define('GENDER', 'Gender');
define('MALE', 'Male');
define('FEMALE', 'FeMale');
define('BASIC_SALARY', 'Basic Salary');
define('EMPLOYEE_LIST', 'Employee List');
define('ATTENDANCE', 'Attendance');
define('SALARY', 'Salary');
define('ATTENDANCE_ADD', 'Add Attendance');
define('MONTH', 'Month');
define('DATE', 'Date');
define('START_TIME', 'Start Time');
define('END_TIME', 'End Time');
define('EMPLOYEE_SAVED', 'Thank You.New employee updated.');
define('ADD_DISCOUNTT','Add Discount');
define('DISCOUNTT','Discount');
define('SPECIAL_PRICE','Special Price');
define('OTHER_PRODUCTS','Other Products');
define('PRICE','Price');
define('DASHBOARD','Dashboard');
define('CONTROL_PANEL','Control panel');
define('FINISHED_ORDERS','Finish Orders');
define('TOTAL_SALES','Total Sales');
define('MORE_INFO','More Info');
?>