<?PHP
define('MAIN_NAVIGATION', 'முக்கிய ஊடுருவல்');
define('INVENTORY', 'சரக்கு');
define('ADD_PRODUCTS', 'பொருட்களை சேர்க்க');
define('HOME', 'முகப்பு');
define('PRODUCT_NAME', 'பொருளின் பெயர்');
define('UNIT_PRICE', 'அலகு விலை');
define('ADD_QUANTITY', 'அளவு சேர்க்க');
define('SELECT_PRODUCT', 'தயாரிப்பு தேர்வு');
define('HUMAN_RESOURCES', 'மனித வளம்');
define('ADD_EMPLOYEE', 'பணியாளர் சேர்');
define('NAME', 'பெயர்');
define('EMAIL', 'மின்னஞ்சல்');
define('ERORR_PROCEED', 'தொடர பிழைகளைத் திருத்தவும்.');
define('PRODUCT_SAVED', 'நன்றி.தயாரிப்பு மேம்படுத்தப்பட்டது.');
define('PLEASE_CHECK', 'தயவுசெய்து சாிபார்க்கவும்');
define('PRODUCTS_LIST', 'தயாரிப்புகள் பட்டியல்');
define('ID', 'ID');
define('EDIT', 'Edit');
define('DELETE', 'Delete');
define('QUANTITY', 'Quantity');
define('SEARCH', 'Search');
define('CUSTOMERS', 'Customers');
define('ADD_CUSTOMERS', 'Add Customers');
define('ACTION', 'Action');
define('ADD', 'Add');
define('SUBSTRACT', 'Subtract');
define('CUSTOMER_NAME', 'Customer Name');
define('ADDRESS', 'Address');
define('TELEPHONE', 'Telephone Number');
define('CUSTOMER_SAVED', 'Thank you.New Customer Updated.');
define('CUSTOMER_LIST', 'Customers List');
define('SALES', 'Sales');
define('ADD_SALE', 'Add Sale');
define('SELECT_CUSTOMER', 'Select Customer');
define('OR_TEXT', 'OR');
define('TAX_APPLICABLE', 'Tax applicable');
define('SALES_LIST', 'Sales List');
define('AMOUNT', 'Amount');
define('VIEW', 'View');
define('STATUS', 'Status');
define('NIC', 'Identity Card Number');
define('BIRTHDAY', 'Birthday');
define('GENDER', 'Gender');
define('MALE', 'Male');
define('FEMALE', 'FeMale');
define('BASIC_SALARY', 'Basic Salary');
define('EMPLOYEE_LIST', 'Employee List');
define('ATTENDANCE', 'Attendance');
define('SALARY', 'Salary');
define('ATTENDANCE_ADD', 'Add Attendance');
define('MONTH', 'Month');
define('DATE', 'Date');
define('START_TIME', 'Start Time');
define('END_TIME', 'End Time');
define('EMPLOYEE_SAVED', 'Thank You.New employee updated.');
define('ADD_DISCOUNTT','Add Discount');
define('DISCOUNTT','Discount');
define('SPECIAL_PRICE','Special Price');
define('OTHER_PRODUCTS','Other Products');
define('PRICE','Price');
define('DASHBOARD','Dashboard');
define('CONTROL_PANEL','Control panel');
define('FINISHED_ORDERS','Finish Orders');
define('TOTAL_SALES','Total Sales');
define('TOTAL_CUSTOMERS','Total Customers');
define('TOTAL_PRODUCTS','Total Products');
define('MORE_INFO','More Info');
define('REVENUE','Revenue');
define('INVOICES','Invoices');
define('PROFILE_CONTROL','Profile Control');
define('LANGUAGE','Language');
?>