<?php
define('MAIN_NAVIGATION', 'ප්‍රදාන මෙනුව');
define('INVENTORY', 'බඩු තොග');
define('ADD_PRODUCTS', 'නිෂ්පාදන එකතු කරන්න');
define('HOME', 'මුල් පිටුව');
define('PRODUCT_NAME', 'නිෂ්පාදන නාමය');
define('UNIT_PRICE', 'ඒකක මිල');
define('ADD_QUANTITY', 'ප්රමාණ එකතු කරන්න');
define('SELECT_PRODUCT', 'නිශ්පදනය තොරන්න');
define('HUMAN_RESOURCES', 'මානව සම්පත්');
define('ADD_EMPLOYEE', 'සේවක එකතු කරන්න');
define('NAME', 'නම');
define('EMAIL', 'විද්යුත් තැපෑල');
define('ERORR_PROCEED', 'ඉදිරියට ගෙන යාම වැරදි නිවැරදි කරන්න.');
define('PRODUCT_SAVED', 'ස්තුතියි නිෂ්පාදන යාවත්කාලීන කිරීම සාර්තකයි.');
define('PLEASE_CHECK', 'කරුණාකර පරික්ෂා කරන්න');
define('PRODUCTS_LIST', 'නිෂ්පාදන ලැයිස්තුව');
define('ID', 'අංකය');
define('EDIT', 'සංස්කරණය');
define('DELETE', 'මකන්න');
define('QUANTITY', 'ප්රමාණය');
define('SEARCH', 'සෙවීම');
define('CUSTOMERS', 'පාරිභෝගිකයන්');
define('ADD_CUSTOMERS', 'ගනුදෙනුකරුවන් එකතු කරන්න');
define('ACTION', 'කටයුතු');
define('ADD', 'එක් කරන්න');
define('SUBSTRACT', 'අඩු කරන්න');
define('CUSTOMER_NAME', 'පාරිභෝගිකයාගේ නම');
define('ADDRESS', 'ලිපිනය');
define('TELEPHONE', 'දුරකථන අංකය');
define('CUSTOMER_SAVED', 'ඔබට ස්තුතියි. පාරිභෝගික සාර්ථකව යාවත්කාලීන කිරීම .');
define('CUSTOMER_LIST', 'පාරිභෝගිකයන් ලැයිස්තුව');
define('SALES', 'විකුණුම්');
define('ADD_SALE', 'විකුණුම් එකතු කරන්න');
define('SELECT_CUSTOMER', 'පාරිභෝගික තෝරන්න');
define('OR_TEXT', 'හෝ');
define('TAX_APPLICABLE', 'බදු අදාළ වන');
define('SALES_LIST', 'විකුණුම් ලැයිස්තු');
define('AMOUNT', 'ප්රමාණය');
define('VIEW', 'බලන්න');
define('STATUS', 'ත්ත්වය');
define('NIC', 'හැඳුනුම්පත් අංකය');
define('BIRTHDAY', 'උපන් දිනය');
define('GENDER', 'ස්ත්රී පුරුෂ භාවය');
define('MALE', 'පිරිමි');
define('FEMALE', 'කාන්තා');
define('BASIC_SALARY', 'මූලික වැටුප');
define('EMPLOYEE_LIST', 'සේවක ලැයිස්තුව');
define('ATTENDANCE', 'පැමිණීම');
define('SALARY', 'වැටුප');
define('ATTENDANCE_ADD', 'පැමිණීම');
define('MONTH', 'මාසය');
define('DATE', 'දිනය');
define('START_TIME', 'ආරම්භක වේලාව');
define('END_TIME', 'අවසන් වේලාව');
define('EMPLOYEE_SAVED', 'ඔබට ස්තුතියි. නව සේවකයන්ට යාවත්කාලීන අවසන් විය.');
?>